name: Build Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Verify gradlew exists
        run: ls -la android/gradlew

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build debug APK
        run: cd android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk


# name: Build Android APK

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     name: Build APK
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: 17


#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: |
#           npm install

#       # - name: Install Android SDK
#       #   uses: reactivecircus/android-emulator-runner@v2
#       #   with:
#       #     api-level: 30
#       #     target: google_apis
#       #     arch: x86_64
#       #     profile: pixel
#       #     script: echo "Android SDK installed"

#       # - name: Grant execute permission to gradlew
#       #   run: chmod +x android/gradlew

#       - name: Build debug APK
#         run: cd android && ./gradlew assembleDebug

#       - name: Upload APK
#         uses: actions/upload-artifact@v4
#         with:
#           name: hello-world-apk
#           path: android/app/build/outputs/apk/debug/app-debug.apk
